# Generated by Django 3.0 on 2021-01-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_page_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='summary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
