name: Inlano Web Deploy
on:
  push:
    branches:
      - inlano-prod
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.DONTLOOP_SERVER }} >> ~/.ssh/known_hosts

      - run: ssh root@${{ secrets.DONTLOOP_SERVER }} 'cd ~/dontloop && git fetch --all && git checkout inlano-prod && git pull && lerna bootstrap && yarn build:utils && yarn build:data && yarn build:ui && yarn build:inlano:web && pm2 reload inlano-web'
