name: Deploy Inlano API
on:
  push:
    branches:
      - master
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.DONTLOOP_SERVER }} >> ~/.ssh/known_hosts

      - run: ssh root@${{ secrets.DONTLOOP_SERVER }} 'cd ~/dontloop-api && git stash && git fetch --all && git checkout master && git pull && docker-compose up -d --build inlano-api'